server:
  port: 8761

spring:
  application:
    name: course-platform-service-registry


course-platform:
  serviceRegistry:
    username: serviceRegistry
    password: 'course-platform123sr'

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: 'http://${course-platform.serviceRegistry.username}:${course-platform.serviceRegistry.password}@localhost:8761/eureka'

