server:
  port: 8080

spring:
  application:
    name: course-platform-api-gateway


  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: authuser-service
              uri: lb://COURSE-PLATFORM-AUTHUSER-SERVICE
              predicates:
                - Path=/course-platform-authuser/**

            - id: course-service
              uri: lb://COURSE-PLATFORM-COURSE-SERVICE
              predicates:
                - Path=/course-platform-course/**

            - id: notification-service
              uri: lb://COURSE-PLATFORM-NOTIFICATION-SERVICE
              predicates:
                - Path=/course-platform-notification/**




eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost