spring:
  application:
    name: course-platform-notification-service
  config:
    import: 'configserver:'
  cloud:
    config:
      discovery:
        service-id: course-platform-config-server
      username: configserver
      password: 'course-platform123cs'
