server:
  port: 8082

spring:
  application:
    name: course-platform-course-service
  datasource:
    url: jdbc:postgresql://localhost:5432/course-microsservice
    username: postgres
    password: 299792458
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob.non-contextual-creation: true
        show_sql: true
        format_sql: true
  output:
    ansi:
      enabled: always


logging:
  level:
    com.victorxavier.course_platform: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

course_platform:
  api:
    url:
      authuser: 'http://course-platform-authuser-service'

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost