server:
  port: 8888

spring:
  application:
    name: course-platform-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/oliver-Victorxavier/course_platform-config-server-repo
          default-label: main
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_TOKEN}


course-platform:
  configserver:
    username: configserver
    password: 'course-platform123cs'
  serviceRegistry:
    username: serviceRegistry
    password: 'course-platform123sr'

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://${course-platform.serviceRegistry.username}:${course-platform.serviceRegistry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost

